### ISSUE TITLE
RuntimeError: error evaluating function `inline-svg`: Cannot read property 'attribs' of null in

### ISSUE THREAD

**Issue by br4nnigan** [atlassian/less-plugin-inline-svg#1]
Throws this error:
    `background-image: inline-svg("../../../../img/checkbox.svg", "my-icon", "fill: blue");`

Works if I don't pass the attribs parameter:
   ` background-image: inline-svg("../../../../img/checkbox.svg", "my-icon");`

Another issue:

this won't work:
   ` lessc --inline-svg`

while this works:
   ` lessc --plugin=less-plugin-inline-svg`

**Comment by br4nnigan** [comment]
Allright, now I got it. Apparently with \<\<ID attribute of SVG node>> you mean that the svg has to have a node with this id to apply the attributes on. Wasn't clear to me.

**Comment by macku** [comment]
> Allright, now I got it. Apparently with <> you mean that the SVG has to have a node with this id to apply the attributes on. Wasn't clear to me.

I guess that GitHub editor swallowed whatever was between `<>` in your comment. 
The use case from the example is about using the same id attribute in both SVG file and Less code so you can match on what SVG node you would like to apply custom styling.

**Comment by br4nnigan** [comment]
> I guess that GitHub editor swallowed whatever was between <> in your comment.

Indeed, I fixed it.
