### ISSUE TITLE
Support Less 3

### ISSUE THREAD

**Issue by runarb** [atlassian/less-plugin-inline-svg#3]
Would be great to have support for Less >= 3.9.0!

https://github.com/less/less.js/blob/master/CHANGELOG.md

**Comment by macku** [comment]
@runarb We are always open for contribution and pull requests.
Does the plugin doesn't work with Less >= 3.9.0? If so, can you please provide us with the errors or exception that can help us add missing compatibility?

**Comment by macku** [comment]
The missing support for Less 3 was added and released [in version 2](https://github.com/atlassian/less-plugin-inline-svg/releases/tag/v2.0.0)
