### ISSUE TITLE
NPM still at version 1.0.0

### ISSUE THREAD

**Issue by euhmeuh** [atlassian/less-plugin-inline-svg#5]
Hello!

On the NPM repository (https://www.npmjs.com/package/less-plugin-inline-svg), the plugin is still in version 1.0.0.

Could you publish the package? Thanks!

**Comment by macku** [comment]
Ups. I forgot to run `npm publsh` last time. Thanks for reporting that.

I've just published version 2.0:
https://www.npmjs.com/package/less-plugin-inline-svg/v/2.0.0
